### ISSUE TITLE
1.21 ?

### ISSUE THREAD

**Issue by SideLo98** [javachefmc/skip-transitions#14]
support for 1.21 version ?

**Comment by javachefmc** [comment]
Apologies for the delay, struggling with updating my IDE

**Comment by javachefmc** [comment]
Added compat for 1.21+ in latest release

**Comment by SideLo98** [comment]
> Added compat for 1.21+ in latest release

can you update in Modrinth as well please

**Comment by javachefmc** [comment]
Modrinth links should be updated as well; version number was not incremented (1.4.0) as code didn't change.

**Comment by javachefmc** [comment]
> I think it broke again on 1.21.3 @javachefmc 

Yes it did 😫
I'm expecting more breakage with the The Garden Awakens update in 4 days. Looking into it though

**Comment by javachefmc** [comment]
https://github.com/javachefmc/skip-transitions/releases/tag/v1.4.0%2Bmc1.21.3
Added a semi-unofficial release but it is clear that more patching will be necessary.

Working:
- Title screen fade in
- Resourcepack fade in/out

Not working:
- Advancement popup
- Chat signing popup
- Transition SFX suppression

**Comment by javachefmc** [comment]
Version 1.5.0 adds compatibility for mc 1.21.3
