### ISSUE TITLE
removeToastsSlide doesn't work

### ISSUE THREAD

**Issue by ghost** [javachefmc/skip-transitions#4]
Hello, the mod loads fine on 1.19.
I was disabling the "removeToastsSlide" option but it doesn't work, I can't see any achievements.
Greetings.

**Comment by trufflezmc** [comment]
I was unable to recreate this issue running skiptransitions-1.3.2+1.18.x on Minecraft 1.19 with Fabric Loader 0.14.8 and Fabric API 0.57.0. Could you describe the issue in more detail?

**Comment by mrniddala** [comment]
Hello, I will look into that when I find time. Maybe a different mod is causing this issue.
Greetings.

**Comment by TGODiamond** [comment]
Any updates, or is this issue stale or irrelevant at this point?

**Comment by javachefmc** [comment]
Issue will be closed due to inactivity
